name: Update changelog

on:
  pull_request:
    types: [opened, reopened]
    branches: [ main, master, trunk ]

env:
  RUST_LOG: DEBUG

jobs:
  update-changelog:
    #if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: crambl/dependabot-changelog-writer@v0.3.0
      with:
        changelog: './CHANGELOG.md'
        version: 'Unreleased'
        push_changes: false

