name: Update changelog

on:
  pull_request:
    types: [opened, reopened]
    branches: [ main, master, trunk ]

jobs:
  update-release-file:
    #if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4


    - uses: crambl/dependabot-changelog-writer@v0.1.0
      with:
        changelog: './CHANGELOG.md'
        version: 'Unreleased'
        token: ${{ secrets.PAT_ACTION_PUSH }}
